spring:
    jackson:
        default-property-inclusion: non_null
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: false
            ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
        mapper:
            ACCEPT_CASE_INSENSITIVE_ENUMS: true
            ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
        parser:
            INCLUDE_SOURCE_IN_LOCATION: true

    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB

server:
    port: 8084
    error:
        whitelabel:
            enabled: false
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain
        min-response-size: 512

management:
    endpoint:
        health:
            show-details: always
        info:
            git:
                mode: full
    endpoints:
        web:
            exposure:
                include: "beans,flyway,health,info,scheduledtasks,mappings"

logging:
    level:
        root: INFO
        com.amazonaws: ERROR
        com.icegreen.greenmail.smtp.SmtpManager: ERROR
        org.springframework: INFO
        org.hibernate: ERROR
        org.hibernate.engine.jdbc.spi.SqlExceptionHelper: OFF
        com.wutsi: DEBUG
        springfox: ERROR

    pattern:
        console: "%d Type=%level Logger=%c Thread=%thread %m%n"
        file: "%d Type=%level Logger=%c Thread=%thread %m%n"

koki:
    webapp:
        client-id: koki-chatbot-telegram
        base-url: http://localhost:${server.port}
        tenant-id: 1

    ai:
        rest:
            read-timeout: 60000 # 1 minute
            connect-timeout: 60000 # 1 miniute
        deepseek:
            api-key: ${DEEPSEEK_API_KEY}
            model: deepseek-chat

    executor:
        thread-pool-size: 16

    rest:
        connection-timeout: 15000
        read-timeout: 15000

    sdk:
        base-url: http://localhost:8080

    telegram:
        bot-name: ${TELEGRAM_CHATBOT}
        token: ${TELEGRAM_TOKEN}

    url:
        bitly:
            api-key: ${BITLY_API_KEY}
