logging:
    level:
        com.wutsi: INFO

koki:
    kpi:
        room:
            daily-cron: "0 0 * * * *"     # Every hour
            monthly-cron: "0 30 5 2 * *"   # Every 2nd of each month at 5:30AM

    persister:
        cron: "0 0 * * * *"  # Flush every hour

    module:
        tracking:
            mq:
                consumer-delay-seconds: 60

wutsi:
    platform:
        cache:
            redis:
                url: ${REDISCLOUD_URL}

        storage:
            type: s3
            s3:
                bucket: com-wutsi-koki-prod
                region: us-east-1
                access-key: ${AWS_ACCESS_KEY}
                secret-key: ${AWS_SECRET_KEY}

        mq:
            type: rabbitmq
            rabbitmq:
                url: ${CLOUDAMQP_URL}
