logging:
    level:
        com.wutsi: INFO

koki:
    rabbitmq:
        url: ${CLOUDAMQP_URL}

    storage:
        type: s3
        s3:
            bucket: com-wutsi-koki-track-test
            region: us-east-1
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}

    module:
        tracking:
            mq:
                consumer-delay-seconds: 60
