INSERT INTO T_LISTING(id, tenant_fk, city_fk, neighbourhood_fk, listing_type, property_type, furniture_type, status, bedrooms, bathrooms, price, sale_price, lot_area, property_area, seller_agent_user_fk, buyer_agent_user_fk)
    VALUES (100, 1, null, null, null, null, null, 0, null, null, null, null,    null, null, null, null),
           (101, 1, null, null, null, null, null, 0, null, null, null, null,    null, null, null, null),
           (102, 1, 2222, null, null, null, null, 0, null, null, null, null,    null, null, null, null),
           (103, 1, null, 3333, null, null, null, 0, null, null, null, null,    null, null, null, null),
           (104, 1, null, null, 2,    null, null, 0, null, null, null, null,    null, null, null, null),
           (105, 1, null, null, null, 1,    null, 0, null, null, null, null,    null, null, null, null),
           (106, 1, null, null, null, null, 2,    0, null, null, null, null,    null, null, null, null),
           (107, 1, null, null, null, null, null, 6, null, null, null, null,    null, null, null, null),
           (108, 1, null, null, null, null, null, 0, 2,    null, null, null,    null, null, null, null),
           (109, 1, null, null, null, null, null, 0, 4,    null, null, null,    null, null, null, null),
           (110, 1, null, null, null, null, null, 0, 1,    null, null, null,    null, null, null, null),
           (111, 1, null, null, null, null, null, 0, null, 2,    null, null,    null, null, null, null),
           (112, 1, null, null, null, null, null, 0, null, 3,    null, null,    null, null, null, null),
           (113, 1, null, null, null, null, null, 0, null, 1,    null, null,    null, null, null, null),
           (114, 1, null, null, null, null, null, 0, null, null, 1000, null,    null, null, null, null),
           (115, 1, null, null, null, null, null, 0, null, null, 1500, null,    null, null, null, null),
           (116, 1, null, null, null, null, null, 0, null, null, 2000, null,    null, null, null, null),
           (117, 1, null, null, null, null, null, 0, null, null, null, null,    1000, null, null, null),
           (118, 1, null, null, null, null, null, 0, null, null, null, null,    1200, null, null, null),
           (119, 1, null, null, null, null, null, 0, null, null, null, null,    2000, null, null, null),
           (120, 1, null, null, null, null, null, 0, null, null, null, null,    null, 1000, null, null),
           (121, 1, null, null, null, null, null, 0, null, null, null, null,    null, 1100, null, null),
           (122, 1, null, null, null, null, null, 0, null, null, null, null,    null, 2000, null, null),
           (123, 1, null, null, null, null, null, 0, null, null, null, null,    null, null, 1234, null),
           (124, 1, null, null, null, null, null, 0, null, null, null, null,    null, null, null, 4567),
           (125, 1, null, null, null, null, null, 0, null, null, null, null,    null, null, 1111, null),
           (126, 1, null, null, null, null, null, 0, null, null, null, null,    null, null, null, 1111),
           (127, 1, null, null, null, null, null, 0, null, null, null, 250000, null, null, null, null),
           (128, 1, null, null, null, null, null, 0, null, null, null, 350000, null, null, null, null),
           (129, 1, null, null, null, null, null, 0, null, null, null, 500000, null, null, null, null),

           (200, 2, null, null, null, null, null, 0, null, null, null, null,    null, null, null, null)
           ;
