package com.wutsi.koki.portal.page

object PageName {
    const val ACCOUNT = "page.account"
    const val ACCOUNT_LIST = "page.account.list"
    const val ACCOUNT_EDIT = "page.account.edit"
    const val ACCOUNT_CREATE = "page.account.create"
    const val ACCOUNT_SETTINGS = "page.settings.account"
    const val ACCOUNT_SETTINGS_ATTRIBUTE = "page.settings.account.attribute"
    const val ACCOUNT_SETTINGS_ATTRIBUTE_IMPORT = "page.settings.account.attribute.import"
    const val ACCOUNT_SETTINGS_ATTRIBUTE_LIST = "page.settings.account.attribute.list"
    const val ACCOUNT_SETTINGS_TYPE = "page.settings.account.type"
    const val ACCOUNT_SETTINGS_TYPE_IMPORT = "page.settings.account.type.import"
    const val ACCOUNT_SETTINGS_TYPE_LIST = "page.settings.account.type.list"

    const val CONTACT = "page.contact"
    const val CONTACT_LIST = "page.contact.list"
    const val CONTACT_EDIT = "page.contact.edit"
    const val CONTACT_CREATE = "page.contact.create"
    const val CONTACT_SETTINGS = "page.contact.settings"
    const val CONTACT_SETTINGS_TYPE = "page.settings.contact.type"
    const val CONTACT_SETTINGS_TYPE_IMPORT = "page.settings.contact.type.import"
    const val CONTACT_SETTINGS_TYPE_LIST = "page.settings.contact.type.list"

    const val EMAIL_SETTINGS = "page.settings.email"
    const val EMAIL_SETTINGS_SMTP = "page.settings.smtp"
    const val EMAIL_SETTINGS_SMTP_EDIT = "page.settings.smtp.edit"
    const val EMAIL_SETTINGS_EMAIL_DECORATOR = "page.settings.email.decorator"
    const val EMAIL_SETTINGS_EMAIL_DECORATOR_EDIT = "page.settings.email.decorator.edit"

    const val ERROR = "page.error"
    const val ERROR_SUSPENDED = "page.error.suspended"

    const val FILE = "page.file"

    const val FORM = "page.form"
    const val FORM_SUBMITTED = "page.form.submitted"

    const val HOME = "page.home"

    const val LOG = "page.log"

    const val LOGIN = "page.login"

    const val SECURITY_SETTINGS = "page.settings.security"
    const val SECURITY_SETTINGS_ROLE = "page.settings.security.role"
    const val SECURITY_SETTINGS_ROLE_CREATE = "page.settings.security.role.create"
    const val SECURITY_SETTINGS_ROLE_EDIT = "page.settings.security.role.edit"
    const val SECURITY_SETTINGS_ROLE_LIST = "page.settings.security.role.list"
    const val SECURITY_SETTINGS_ROLE_PERMISSION = "page.settings.security.role.permission"
    const val SECURITY_SETTINGS_USER = "page.settings.security.user"
    const val SECURITY_SETTINGS_USER_CREATE = "page.settings.security.user.create"
    const val SECURITY_SETTINGS_USER_EDIT = "page.settings.security.user.edit"
    const val SECURITY_SETTINGS_USER_LIST = "page.settings.security.user.list"
    const val SECURITY_SETTINGS_USER_ROLE = "page.settings.security.user.role"

    const val SETTINGS_MESSAGE = "page.settings.message"
    const val SETTINGS_MESSAGE_CREATE = "page.settings.message.create"
    const val SETTINGS_MESSAGE_DELETED = "page.settings.message.deleted"
    const val SETTINGS_MESSAGE_EDIT = "page.settings.message.edit"
    const val SETTINGS_MESSAGE_LIST = "page.settings.message.list"
    const val SETTINGS_MESSAGE_SAVED = "page.settings.message.saved"

    const val SETTINGS = "page.settings"
    const val SETTINGS_FORM = "page.settings.form"
    const val SETTINGS_FORM_CREATE = "page.settings.form.create"
    const val SETTINGS_FORM_DELETED = "page.settings.form.deleted"
    const val SETTINGS_FORM_EDIT = "page.settings.form.edit"
    const val SETTINGS_FORM_LIST = "page.settings.form.list"
    const val SETTINGS_FORM_SAVED = "page.settings.form.saved"
    const val SETTINGS_FORM_SUBMISSION = "page.settings.form.submission"
    const val SETTINGS_SERVICE = "page.settings.service"
    const val SETTINGS_SERVICE_CREATE = "page.settings.service.create"
    const val SETTINGS_SERVICE_DELETED = "page.settings.service.deleted"
    const val SETTINGS_SERVICE_EDIT = "page.settings.service.edit"
    const val SETTINGS_SERVICE_LIST = "page.settings.service.list"
    const val SETTINGS_SERVICE_SAVED = "page.settings.service.saved"
    const val SETTINGS_SCRIPT = "page.settings.script"
    const val SETTINGS_SCRIPT_CREATE = "page.settings.script.create"
    const val SETTINGS_SCRIPT_RUN = "page.settings.script.run"
    const val SETTINGS_SCRIPT_DELETED = "page.settings.script.deleted"
    const val SETTINGS_SCRIPT_EDIT = "page.settings.script.edit"
    const val SETTINGS_SCRIPT_LIST = "page.settings.script.list"
    const val SETTINGS_SCRIPT_SAVED = "page.settings.script.saved"
    const val SETTINGS_WORKFLOW = "page.settings.workflow"
    const val SETTINGS_WORKFLOW_ACTIVITY = "page.settings.workflow.activity"
    const val SETTINGS_WORKFLOW_CREATE = "page.settings.workflow.create"
    const val SETTINGS_WORKFLOW_EDIT = "page.settings.workflow.edit"
    const val SETTINGS_WORKFLOW_LIST = "page.settings.workflow.list"
    const val SETTINGS_WORKFLOW_SAVED = "page.settings.workflow.saved"
    const val SETTINGS_WORKFLOW_START = "page.settings.workflow.start"
    const val SETTINGS_WORKFLOW_STARTED = "page.settings.workflow.started"

    const val TASK = "page.task"
    const val TASK_COMPLETED = "page.task.completed"

    const val TAX = "page.tax"
    const val TAX_LIST = "page.tax.list"
    const val TAX_EDIT = "page.tax.edit"
    const val TAX_CREATE = "page.tax.create"
    const val TAX_STATUS = "page.tax.status"
    const val TAX_SETTINGS = "page.tax.settings"
    const val TAX_SETTINGS_TYPE = "page.settings.tax.type"
    const val TAX_SETTINGS_TYPE_IMPORT = "page.settings.tax.type.import"
    const val TAX_SETTINGS_TYPE_LIST = "page.settings.tax.type.list"

    const val UPLOAD = "upload"

    const val WORKFLOW = "page.workflow"
    const val WORKFLOW_ACTIVITY = "page.activity"
    const val WORKFLOW_ACTIVITY_COMPLETED = "page.activity.completed"
    const val WORKFLOW_LIST = "page.workflow.list"
}
