koki:
    sdk:
        base-url: ${KOKI_SERVER_URL}

    storage:
        type: s3
        s3:
            bucket: com-wutsi-koki-test
            region: us-east-1
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}
<<<<<<< Updated upstream
=======

    toggles:
        paypal: false
        mobile-money: false
>>>>>>> Stashed changes
