koki:
    webapp:
        asset-url: https://com-wutsi-koki-test.s3.amazonaws.com/static/koki-portal

    sdk:
        base-url: ${KOKI_SERVER_URL}

    storage:
        type: s3
        s3:
            bucket: com-wutsi-koki-test
            region: us-east-1
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}

    toggles:
        paypal: false
        mobile-money: false
