koki:
    webapp:
        asset-url: https://com-wutsi-koki-test.s3.amazonaws.com/static/koki-portal
    sdk:
        base-url: ${KOKI_SERVER_URL}
    toggles:
        paypal: false
        mobile-money: false

wutsi:
    platform:
        cache:
            type: redis
            redis:
                url: ${REDISCLOUD_URL}
        storage:
            type: s3
            s3:
                bucket: com-wutsi-koki-prod
                region: us-east-1
                access-key: ${AWS_ACCESS_KEY}
                secret-key: ${AWS_SECRET_KEY}
