package com.wutsi.koki.room.dto

import com.wutsi.koki.refdata.dto.Address
import com.wutsi.koki.refdata.dto.Money
import java.util.Date

data class Room(
    val id: Long = -1,
    val accountId: Long = -1,
    val heroImageId: Long? = null,
    val type: RoomType = RoomType.UNKNOWN,
    val status: RoomStatus = RoomStatus.UNKNOWN,
    val title: String? = null,
    val summary: String? = null,
    val description: String? = null,
    val numberOfRooms: Int = -1,
    val numberOfBathrooms: Int = -1,
    val numberOfBeds: Int = -1,
    val maxGuests: Int = -1,
    val area: Int = -1,
    val pricePerNight: Money? = null,
    val pricePerMonth: Money? = null,
    val neighborhoodId: Long? = null,
    val address: Address? = null,
    val checkinTime: String? = null,
    val checkoutTime: String? = null,
    val longitude: Double? = null,
    val latitude: Double? = null,
    val createdById: Long? = null,
    val createdAt: Date = Date(),
    val modifiedById: Long? = null,
    val modifiedAt: Date = Date(),
    val publishedById: Long? = null,
    val publishedAt: Date? = null,
    val amenityIds: List<Long> = emptyList(),
    val furnishedType: FurnishedType = FurnishedType.UNKNOWN,
    val leaseType: LeaseType = LeaseType.UNKNOWN,
    val categoryId: Long? = null,
    val listingUrl: String? = null,
    val leaseTerm: LeaseTerm = LeaseTerm.UNKNOWN,
    val leaseTermDuration: Int? = null,
    val advanceRent: Int? = null,
    val visitFees: Money? = null,
    val yearOfConstruction: Int? = null,
    val dateOfAvailability: Date? = null,
)
