spring:
    flyway:
        clean-disabled: false
        locations: "classpath:db/migration/common,classpath:db/migration/test"
    jpa:
        show-sql: false
    datasource:
        url: ${SPRING_DATABASE_URL}
        username: ${SPRING_DATABASE_USERNAME}
        password: ${SPRING_DATABASE_PASSWORD}

swagger:
    protocol: https

koki:
    rabbitmq:
        url: ${CLOUDAMQP_URL}

    storage:
        type: aws
        aws:
            bucket: koki-test
            region: us-east1
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}
