spring:
    jackson:
        default-property-inclusion: non_null
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: false
            ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
        mapper:
            ACCEPT_CASE_INSENSITIVE_ENUMS: true
            ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
        parser:
            INCLUDE_SOURCE_IN_LOCATION: true

    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB

server:
    port: 8085
    error:
        whitelabel:
            enabled: false
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain
        min-response-size: 512

management:
    endpoint:
        health:
            show-details: always
        info:
            git:
                mode: full
    endpoints:
        web:
            exposure:
                include: "beans,flyway,health,info,scheduledtasks,mappings"

logging:
    level:
        root: INFO
        springfox: ERROR
        com.wutsi: DEBUG

    pattern:
        console: "%d Type=%level Logger=%c Thread=%thread %m%n"
        file: "%d Type=%level Logger=%c Thread=%thread %m%n"

koki:
    webapp:
        client-id: koki-chatbot-messenger
        base-url: http://localhost:${server.port}
        tenant-id: 1

    ai:
        rest:
            read-timeout: 60000 # 1 minute
            connect-timeout: 60000 # 1 miniute
        deepseek:
            api-key: ${DEEPSEEK_API_KEY}
            model: deepseek-chat

    executor:
        thread-pool-size: 16

    rabbitmq:
        url: amqp://localhost
        exchange-name: koki-tracking
        max-retries: 24
        ttl-seconds: 84600

    rest:
        connection-timeout: 15000
        read-timeout: 15000

    sdk:
        base-url: http://localhost:8080

    storage:
        type: local # local | s3
        local:
            directory: ${user.home}/__wutsi
            base-url: http://localhost:${server.port}
            servlet-path: /local-storage
        s3:
            bucket: koki-test
            region: us-east-1
            access-key: ""
            secret-key: ""

    messenger:
        token: ${MESSENGER_TOKEN}
        verify-token: ${MESSENGER_VERIFY_TOKEN}
