ALTER TABLE T_MESSAGE ADD COLUMN country VARCHAR(2);
ALTER TABLE T_MESSAGE ADD COLUMN language VARCHAR(2);
ALTER TABLE T_MESSAGE ADD COLUMN sender_account_fk BIGINT;

CREATE INDEX sender_account ON T_MESSAGE(sender_account_fk);
