DROP TABLE T_TAX_PRODUCT;
DROP TABLE T_TAX_FILE;
DROP TABLE T_TAX;

DELETE FROM T_ROLE_PERMISSION where permission_fk IN (SELECT id FROM T_PERMISSION WHERE module_fk=180);
DELETE FROM T_PERMISSION WHERE module_fk=180;

DELETE FROM T_TENANT_MODULE WHERE module_fk=180;
DELETE FROM T_MODULE WHERE id=180;

ALTER TABLE T_INVOICE DROP COLUMN tax_fk;
