DROP TABLE T_FORM_OWNER;
DROP TABLE T_FORM;

DELETE FROM T_ROLE_PERMISSION where permission_fk IN (SELECT id FROM T_PERMISSION WHERE module_fk=220);
DELETE FROM T_PERMISSION WHERE module_fk=220;

DELETE FROM T_TENANT_MODULE WHERE module_fk=220;
DELETE FROM T_MODULE WHERE id=220;
