ALTER TABLE T_AMENITY ADD COLUMN name_fr TEXT;

ALTER TABLE T_CATEGORY ADD COLUMN name_fr TEXT;
ALTER TABLE T_CATEGORY ADD COLUMN long_name_fr TEXT;

ALTER TABLE T_ROOM ADD COLUMN title_fr TEXT;
ALTER TABLE T_ROOM ADD COLUMN summary_fr TEXT;
ALTER TABLE T_ROOM ADD COLUMN description_fr TEXT;

ALTER TABLE T_FILE ADD COLUMN title_fr TEXT;
ALTER TABLE T_FILE ADD COLUMN description_fr TEXT;
