DROP TABLE T_AGENT_METRIC;

ALTER TABLE T_AGENT DROP COLUMN total_sales;
ALTER TABLE T_AGENT DROP COLUMN total_rentals;
ALTER TABLE T_AGENT DROP COLUMN total_transactions;
ALTER TABLE T_AGENT DROP COLUMN past_12m_rentals;
ALTER TABLE T_AGENT DROP COLUMN past_12m_sales;
ALTER TABLE T_AGENT DROP COLUMN past_12m_transactions;
ALTER TABLE T_AGENT DROP COLUMN last_sold_at;
