DROP TABLE T_NOTE_OWNER;
DROP TABLE T_NOTE;

DELETE FROM T_ROLE_PERMISSION  where permission_fk IN (SELECT id FROM T_PERMISSION where module_fk=140);
DELETE FROM T_PERMISSION where module_fk=140;
DELETE FROM T_MODULE where id=140;
