DROP TABLE T_OFFER_STATUS;
DROP TABLE T_OFFER_VERSION;
DROP TABLE T_OFFER;

DELETE FROM T_ROLE_PERMISSION WHERE permission_fk IN (SELECT id FROM T_PERMISSION where module_fk=280);
DELETE FROM T_PERMISSION where module_fk=280;
DELETE FROM T_TENANT_MODULE where module_fk=280;
DELETE FROM T_MODULE where id=280;

ALTER TABLE T_LISTING DROP COLUMN total_offers;
