DELETE FROM T_NOTE_OWNER;
DELETE FROM T_NOTE;

DELETE FROM T_FILE;

DELETE FROM T_CONTACT;

DELETE FROM T_ACCOUNT_ATTRIBUTE;
DELETE FROM T_ACCOUNT;
DELETE FROM T_ATTRIBUTE;

DELETE FROM T_OFFER_STATUS;
UPDATE T_OFFER set version_fk=null;
DELETE FROM T_OFFER_VERSION;
DELETE FROM T_OFFER;

UPDATE T_LEAD set last_message_fk=null;
DELETE FROM T_LEAD_MESSAGE;
DELETE FROM T_LEAD;

DELETE FROM T_AI_LISTING;
DELETE FROM T_LISTING_STATUS;
DELETE FROM T_LISTING_SEQUENCE;
DELETE FROM T_LISTING_AMENITY;
DELETE FROM T_LISTING;

DELETE FROM T_AGENT_METRIC;
DELETE FROM T_AGENT;

DELETE FROM T_USER_ROLE;
DELETE FROM T_ROLE_PERMISSION;
DELETE FROM T_ROLE;
DELETE FROM T_PASSWORD_RESET_TOKEN;
DELETE FROM T_USER;
DELETE FROM T_INVITATION;

DELETE FROM T_TYPE;
DELETE FROM T_TENANT_MODULE;
DELETE FROM T_CONFIGURATION;
DELETE FROM T_TENANT;

DELETE FROM T_PERMISSION;
DELETE FROM T_MODULE;

DELETE FROM T_PLACE_RATING;
DELETE FROM T_PLACE;

DELETE FROM T_LOCATION;
DELETE FROM T_AMENITY;

UPDATE T_CATEGORY set parent_fk=null;
DELETE FROM T_CATEGORY;
