DELETE FROM T_WI_APPROVAL;
DELETE FROM T_WI_ACTIVITY;
DELETE FROM T_WI_PARTICIPANT;
DELETE FROM T_WI_PARAMETER;
DELETE FROM T_WI_STATE;
DELETE FROM T_WORKFLOW_INSTANCE;

DELETE FROM T_ACTIVITY_PREDECESSOR;
DELETE FROM T_ACTIVITY;
DELETE FROM T_WORKFLOW;

DELETE FROM T_USER_ROLE;
DELETE FROM T_ROLE;
DELETE FROM T_USER;

DELETE FROM T_CONFIGURATION;
DELETE FROM T_ATTRIBUTE;

DELETE FROM T_TENANT;
