DELETE FROM T_ACTIVITY_PRECEDENT;
DELETE FROM T_ACTIVITY;
DELETE FROM T_WORKFLOW;

DELETE FROM T_USER_ROLE;
DELETE FROM T_ROLE;
DELETE FROM T_USER;

DELETE FROM T_CONFIGURATION;
DELETE FROM T_ATTRIBUTE;

DELETE FROM T_TENANT;
