koki:
    sdk:
        base-url: ${KOKI_SERVER_URL}

    rabbitmq:
        url: ${CLOUDAMQP_URL}

    storage:
        type: s3
        s3:
            bucket: com-wutsi-koki-test
            region: us-east-1
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}
