koki:
    webapp:
        asset-url: https://com-wutsi-koki-prod.s3.amazonaws.com/static/koki-room-web

    sdk:
        base-url: ${KOKI_SERVER_URL}

    rabbitmq:
        url: ${CLOUDAMQP_URL}

    storage:
        type: s3
        s3:
            bucket: com-wutsi-koki-prod
            region: us-east-1
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}
