name: pull_request

on:
    pull_request:
        paths:
            - 'pom.xml'
            - 'settings.xml'
            - '.github/workflows/_pr.yml'

jobs:
    build:

        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:9.3
                env:
                    MYSQL_USER: admin
                    MYSQL_PASSWORD: admin
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: koki
                ports:
                    - 3306:3306
            rabbitmq:
                image: rabbitmq:4.1
                env:
                    RABBITMQ_DEFAULT_USER: guest
                    RABBITMQ_DEFAULT_PASS: guest
                ports:
                    - 5672:5672

        steps:
            -   uses: actions/checkout@v4

            -   name: JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17


            -   name: Build
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                    GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY_TEST}}
                    STRIPE_API_KEY: ${{secrets.STRIPE_API_KEY_TEST}}
                    DEEPSEEK_API_KEY: ${{secrets.DEEPSEEK_API_KEY_TEST}}
                    BITLY_API_KEY: ${{secrets.BITLY_API_KEY_TEST}}
                    TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN_TEST}}
                    TELEGRAM_CHATBOT: ${{secrets.TELEGRAM_CHATBOT_TEST}}
                run: |
                    mvn -s settings.xml validate
                    mvn -q -s settings.xml --non-recursive install
                    mvn -Dspring.datasource.username=root -Dspring.datasource.password=root -Dheadless=true -T1C -q -s settings.xml package
