name: pull_request

on:
    pull_request:
        paths:
            - 'pom.xml'
            - 'settings.xml'
            - '.github/workflows/_pr.yml'

jobs:
    build:

        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:9.1
                env:
                    MYSQL_USER: admin
                    MYSQL_PASSWORD: admin
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: koki
                ports:
                    - 3306:3306

        steps:
            -   uses: actions/checkout@v4

            -   name: JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17


            -   name: Build
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                run: |
                    mvn -s settings.xml validate
                    mvn -q -s settings.xml --non-recursive install
                    mvn -Dspring.datasource.username=root -Dspring.datasource.password=root -Dheadless=true -T1C -q -s settings.xml package
