name: koki-portal

on:
    push:
        branches:
            - master
        paths:
            - 'modules/koki-portal/**'
            - '.github/workflows/koki-portal-master.yml'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   name: Install Chromium
                run: sudo apt-get install chromium-browser

            -   name: Build
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                run: |
                    mvn -q -s settings.xml --non-recursive install
                    cd modules/koki-portal
                    mvn -q -s ../../settings.xml install

            -   name: Generate JaCoCo Badge
                uses: cicirello/jacoco-badge-generator@v2
                with:
                    generate-branches-badge: false
                    jacoco-csv-file: modules/koki-portal/target/site/jacoco/jacoco.csv
                    coverage-badge-filename: koki-portal-jococo.svg

            -   name: Commit the badge (if it changed)
                run: |
                    if [[ `git status --porcelain` ]]; then
                      git config user.email "actions@github.com"
                      git config user.name "GitHub Actions"
                      git add -A
                      git commit -m "Autogenerated JaCoCo coverage badge"
                      git push
                    fi
