name: koki-chatbot

on:
    push:
        branches:
            - master
        paths:
            - 'modules/koki-chatbot/**'
            - '.github/workflows/koki-chatbot-master.yml'

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17
            -   name: Set up Maven
                uses: stCarolas/setup-maven@v4.5
                with:
                    maven-version: 3.8.2
            -   name: Build
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                    DEEPSEEK_API_KEY: ${{secrets.DEEPSEEK_API_KEY_TEST}}
                run: |
                    mvn -s settings.xml --non-recursive install
                    cd modules/koki-chatbot
                    git config user.email "actions@github.com"
                    git config user.name "GitHub Actions"
                    git pull
                    mvn -q -B -X release:prepare release:perform

            -   name: Upload JaCoCo Report
                uses: actions/upload-artifact@v4
                with:
                    name: jacoco-report
                    path: modules/koki-chatbot/target/site/jacoco/**/*

            -   name: Generate JaCoCo Badge
                uses: cicirello/jacoco-badge-generator@v2
                with:
                    generate-branches-badge: false
                    jacoco-csv-file: modules/koki-chatbot/target/site/jacoco/jacoco.csv
                    coverage-badge-filename: koki-platform-jococo.svg

            -   name: Commit the badge (if it changed)
                continue-on-error: true
                run: |
                    if [[ `git status --porcelain` ]]; then
                      git config user.email "actions@github.com"
                      git config user.name "GitHub Actions"
                      git add -A
                      git commit -m "Autogenerated JaCoCo coverage badge"
                      git push
                    fi

