name: koki-chatbot-telegram


on:
    push:
        branches:
            - master
        paths:
            - 'modules/koki-chatbot-telegram/**'
            - '.github/workflows/koki-chatbot-telegram-master.yml'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   name: Build
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                    DEEPSEEK_API_KEY: ${{secrets.DEEPSEEK_API_KEY_TEST}}
                    TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN_TEST}}
                    TELEGRAM_CHATBOT: ${{secrets.TELEGRAM_CHATBOT_TEST}}
                run: |
                    mvn -q -s settings.xml --non-recursive install
                    cd modules/koki-chatbot-telegram
                    mvn -q -s ../../settings.xml install

            -   name: Upload app bundle
                uses: actions/upload-artifact@v4
                with:
                    name: appbundle
                    path: modules/koki-chatbot-telegram/target/*.jar

            -   name: Generate JaCoCo Badge
                uses: cicirello/jacoco-badge-generator@v2
                with:
                    generate-branches-badge: false
                    jacoco-csv-file: modules/koki-chatbot-telegram/target/site/jacoco/jacoco.csv
                    coverage-badge-filename: koki-chatbot-telegram-jococo.svg

            -   name: Commit the badge (if it changed)
                continue-on-error: true
                run: |
                    if [[ `git status --porcelain` ]]; then
                      git config user.email "actions@github.com"
                      git config user.name "GitHub Actions"
                      git add -A
                      git commit -m "Autogenerated JaCoCo coverage badge"
                      git push
                    fi

            -   name: HerokuCLI
                run: |
                    curl https://cli-assets.heroku.com/install.sh | sh
                    heroku plugins:install @heroku-cli/plugin-java

            -   name: Get artifact
                uses: actions/download-artifact@v4
                with:
                    name: appbundle

            -   name: Heroku-Deploy-Test
                env:
                    HEROKU_APP: koki-chatbot-telegram-test
                    KOKI_SERVER_URL: ${{secrets.KOKI_SERVER_URL_TEST}}
                    HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY_TEST}}
                    DEEPSEEK_API_KEY: ${{secrets.DEEPSEEK_API_KEY_TEST}}
                    TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN_TEST}}
                    TELEGRAM_CHATBOT: ${{secrets.TELEGRAM_CHATBOT_TEST}}
                    BITLY_API_KEY: ${{secrets.BITLY_API_KEY_TEST}}
                run: |
                    heroku apps | grep ${HEROKU_APP} && echo 'app: ${HEROKU_APP} exists' ||  heroku apps:create ${HEROKU_APP}
                    heroku buildpacks:clear --app ${HEROKU_APP}
                    heroku buildpacks:add heroku/jvm --app ${HEROKU_APP}
                    heroku config:set --app ${HEROKU_APP} APP_PROFILE=test
                    heroku config:set --app ${HEROKU_APP} TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
                    heroku config:set --app ${HEROKU_APP} TELEGRAM_CHATBOT=${TELEGRAM_CHATBOT}
                    heroku config:set --app ${HEROKU_APP} DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
                    heroku config:set --app ${HEROKU_APP} KOKI_SERVER_URL=${KOKI_SERVER_URL}
                    heroku config:set --app ${HEROKU_APP} BITLY_API_KEY=${BITLY_API_KEY}
                    heroku addons -a ${HEROKU_APP} | grep papertrail && echo 'addon: papertrail exists' ||  heroku addons:create papertrail -a ${HEROKU_APP}
                    cp modules/koki-chatbot-telegram/system.properties .
                    cp modules/koki-chatbot-telegram/Procfile .
                    heroku deploy:jar koki-chatbot-telegram.jar --app ${HEROKU_APP}

            -   name: Health check
                env:
                    APP_URL: ${{secrets.KOKI_CHATBOT_TELEGRAM_URL_TEST}}
                run: |
                    sleep 45
                    echo ${APP_URL}
                    curl -sSf ${APP_URL}/actuator/health >> /dev/null
