name: koki-portal

on:
    push:
        branches:
            - master
        paths:
            - 'modules/koki-portal/**'
            - '.github/workflows/koki-portal-master.yml'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   name: Install Chromium
                run: sudo apt-get install chromium-browser

            -   name: Build
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                run: |
                    mvn -q -s settings.xml --non-recursive install
                    cd modules/koki-portal
                    mvn -s ../../settings.xml install -Dheadless=true

            -   name: Upload app bundle
                uses: actions/upload-artifact@v4
                with:
                    name: appbundle
                    path: modules/koki-portal/target/*.jar

            -   name: Generate JaCoCo Badge
                uses: cicirello/jacoco-badge-generator@v2
                with:
                    generate-branches-badge: false
                    jacoco-csv-file: modules/koki-portal/target/site/jacoco/jacoco.csv
                    coverage-badge-filename: koki-portal-jococo.svg

            -   name: Commit the badge (if it changed)
                continue-on-error: true
                run: |
                    if [[ `git status --porcelain` ]]; then
                      git config user.email "actions@github.com"
                      git config user.name "GitHub Actions"
                      git add -A
                      git commit -m "Autogenerated JaCoCo coverage badge"
                      git push
                    fi

            -   name: HerokuCLI
                run: |
                    curl https://cli-assets.heroku.com/install.sh | sh
                    heroku plugins:install @heroku-cli/plugin-java

            -   name: Get artifact
                uses: actions/download-artifact@v4
                with:
                    name: appbundle

            -   name: Heroku-Deploy-Test
                env:
                    HEROKU_APP: koki-portal-test
                    HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY_TEST}}
                    AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_TEST}}
                    AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY_TEST}}
                    KOKI_SERVER_URL: ${{secrets.KOKI_SERVER_URL_TEST}}
                run: |
                    heroku apps | grep ${HEROKU_APP} && echo 'app: ${HEROKU_APP} exists' ||  heroku apps:create ${HEROKU_APP}
                    heroku buildpacks:clear --app ${HEROKU_APP}
                    heroku buildpacks:add heroku/jvm --app ${HEROKU_APP}
                    heroku config:set --app ${HEROKU_APP} APP_PROFILE=test
                    heroku config:set --app ${HEROKU_APP} AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
                    heroku config:set --app ${HEROKU_APP} AWS_SECRET_KEY=${AWS_SECRET_KEY}
                    heroku config:set --app ${HEROKU_APP} KOKI_SERVER_URL=${KOKI_SERVER_URL}
                    heroku addons -a ${HEROKU_APP} | grep papertrail && echo 'addon: papertrail exists' ||  heroku addons:create papertrail -a ${HEROKU_APP}
                    cp modules/koki-portal/system.properties .
                    cp modules/koki-portal/Procfile .
                    heroku deploy:jar koki-portal.jar --app ${HEROKU_APP}

            -   name: S3-Deploy-Test
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_TEST }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_TEST }}
                run: |
                    aws s3 sync \
                      --acl public-read \
                      --region us-east-1 \
                      modules/koki-portal/target/classes/public/ s3://com-wutsi-koki-test/static/koki-portal

            -   name: Health check
                env:
                    APP_URL: ${{secrets.KOKI_PORTAL_URL_TEST}}
                run: |
                    sleep 45
                    echo ${APP_URL}
                    curl -sSf ${APP_URL}/actuator/health >> /dev/null
