name: koki-tracking-server-pr

on:
    pull_request:
        paths:
            - 'modules/koki-tracking-server/**'
            - '.github/workflows/koki-tracking-server-pr.yml'

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            rabbitmq:
                image: rabbitmq:4.1
                env:
                    RABBITMQ_DEFAULT_USER: guest
                    RABBITMQ_DEFAULT_PASS: guest
                ports:
                    - 5672:5672

        steps:
            -   uses: actions/checkout@v4
            -   name: JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17
            -   name: Build
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                run: |
                    mvn -q -s settings.xml --non-recursive install
                    cd modules/koki-tracking-server
                    mvn -Dspring.datasource.username=root -Dspring.datasource.password=root -q -s ../../settings.xml package

            -   name: Add coverage to PR
                id: jacoco
                uses: madrapps/jacoco-report@v1.7.2
                with:
                    paths: |
                        ${{ github.workspace }}/modules/koki-tracking-server/target/site/jacoco/jacoco.xml
                    token: ${{ secrets.GITHUB_TOKEN }}
                    min-coverage-overall: 90
                    min-coverage-changed-files: 90

            -   name: Upload JaCoCo Report
                uses: actions/upload-artifact@v4
                with:
                    name: jacoco-report
                    path: modules/koki-tracking-server/target/site/jacoco/**/*
