name: koki-room-web-pr

on:
    pull_request:
        paths:
            - 'modules/koki-room-web/**'
            - '.github/workflows/koki-room-web-pr.yml'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   name: Install Chromium
                run: sudo apt-get install chromium-browser

            -   name: Build
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                run: |
                    mvn -q -s settings.xml --non-recursive install
                    cd modules/koki-room-web
                    mvn -s ../../settings.xml clean package -Dheadless=true

            -   name: Add coverage to PR
                id: jacoco
                uses: madrapps/jacoco-report@v1.7.2
                with:
                    paths: |
                        ${{ github.workspace }}/modules/koki-room-web/target/site/jacoco/jacoco.xml
                    token: ${{ secrets.GITHUB_TOKEN }}
                    min-coverage-overall: 90
                    min-coverage-changed-files: 90
